// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

// `.env.ts` is generated by the `npm run env` command
// import env from './.env';
import { myEnergyServices } from './myenergy-services';
import { services } from './services';

export const environment = {
  stroyblockUrl:
    'https://api.storyblok.com/v2/cdn/stories/test?token=b3sqRHiuBmK6Bdu0qlK1zQtt&version=published',
  production: false,
  decimalFormat: '1.2-2',
  integerFormat: '1.0-0',
  defaultPrecision: 2,
  project: 'myenergy',
  version: '1.0.0' + '-dev',
  serverUrl: 'https://lcdev.circular-iq.com/api',
  serverUrlShort: 'test-be',
  defaultLanguage: 'English',
  supportedLanguages: ['English', 'Türkçe'],
  reportHost: 'https://report-fe.circular-iq.com',
  services: services,
  myEnergyServices: myEnergyServices,
};
